bootstrap_url: http://blin-dcos-ee.oss-cn-shanghai.aliyuncs.com/2.0.0
cluster_name: aliyun-dcos-ee
exhibitor_storage_backend: static
master_discovery: static
master_list:
- 10.0.4.1
security: permissive
fault_domain_enabled: false
resolvers:
- 100.100.2.136
- 100.100.2.138
